INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(1,
"Disneyland",
"A",
"img/disneyland.jpeg",
2999.99,
"Travel to the first theme park opened by the Walt Disney Company at Anaheim, California in 1955",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(2,
"Hawaii",
"A",
"img/hawaii.jpeg",
1499.99,
"Discover the beauty, culture and adventures waiting for you on the Hawaiian Islands.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(3,
"New Orleans",
"A",
"img/newOrleans.jpeg",
2499.99,
"Visit the world-renowned city for its distinctive music, Creole cuisine, unique dialects, and its annual celebrations and festivals, most notably Mardi Gras.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(4,
"Maui",
"A",
"img/maui.jpeg",
3999.99,
"The Islands of Maui Nui are more than sand and surf destinations. Myriad amenities including world-class resorts, award-winning cuisine, stunning natural beauty, and a plethora of activities.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(5,
"Las Vegas",
"A",
"img/lasVegas.jpeg",
1899.99,
"Travel to a city that was made for entertainment, carved out of the Mojave Desert with escape in mind. It has a lot to offer for visitors, including a vibrant downtown, events, beautiful parks and more.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(6,
"Caribbean",
"A",
"img/caribbean.jpeg",
3999.99,
"Cruise to unforgettable destinations with Royal Caribbean. Save with the best cruise deals and packages to the Caribbean and the Bahamas.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(7,
"Italy",
"A",
"img/italy.jpeg",
4499.99,
"Get ready to explore beautiful destinations, learn about ancient cultures and savour the most loved cuisine in the world.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(8,
"Paris",
"A",
"img/paris.jpeg",
4499.99,
"Discover France's capital, a major European city and a global center for art, fashion, gastronomy and culture. Beyond such landmarks as the Eiffel Tower and the 12th-century, Gothic Notre-Dame cathedral, the city is known for its cafe culture.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(9,
"London",
"A",
"img/london.jpeg",
3499.99,
"Visit some of the top attractions outside of London on this day trip to Stonehenge, Windsor Castle and the historic town of Bath.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(10,
"Australia",
"A",
"img/australia.jpeg",
6999.99,
"Fall in love with the hazy sunset over dusty outback plains, walk through the vibrant alleyways of Melbourne, go swimming with bountiful marine life in the Great Barrier Reef, or enjoy a sensational dinner cruise on Sydney Harbour.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(11,
"Bookings",
"B",
"img/Bookings.jpeg",
29.99,
"Save time when scheduling with Softsol Bookings. Customize appointment details, booking requirements, and specify service providers to streamline the booking experience for you and your customers. Bookings is integrated with your Softsol calendar to help",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(12,
"Browser",
"B",
"img/Browser.jpeg",
39.99,
"Softsol Browser is the best browser for Windows. Sync your passwords, favorites, and settings across multiple devices and start using Softsol Browser today.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(13,
"Code Editor",
"B",
"img/CodeEditor.jpeg",
39.99,
"Configure and theme just like you would expect from any modern development tool. Whether you choose one of the default themes already installed or explore new themes from the Softsol Marketplace, you have the freedom to make your editor or IDE truly yours",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(14,
"Sharing",
"B",
"img/FileSharing.jpeg",
19.99,
"Share and manage content, knowledge, and applications to empower teamwork, quickly find information, and seamlessly collaborate across the organization.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(15,
"Drive",
"B",
"img/Drive.jpeg",
29.99,
"Access and protect your business and school work with this intelligent files app. Share and collaborate from anywhere, on any device.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(16,
"Powerpoint",
"B",
"img/Powerpoint.jpeg",
39.99,
"Create well-designed, impactful slides with the help of Designer and Ideas in PowerPoint. Now you can easily insert 3D objects and embedded animations directly into PowerPoint decks from your own files or a library of content.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(17,
"Chat",
"B",
"img/Chat.jpeg",
49.99,
"Stay connected and access shared content any time to learn, plan, and innovate�together. Share your screen, change or blur your background, and use together mode to virtually be in the same space.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(18,
"Drawing",
"B",
"img/Drawing.jpeg",
39.99,
"Transform the way you use and visualize data so you can bring your best ideas to life. With dozens of ready-to-use templates and thousands of customizable shapes, Softsol Drawing makes it easy�and fun�to create powerful visuals.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(19,
"Video",
"B",
"img/Video.jpeg",
39.99,
"Show exactly what you mean with explainer videos by recording yourself and the screen. Plus, you can add text, drawings, and effects to personalize your videos.",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(20,
"Mail",
"B",
"img/Mail.jpeg",
59.99,
"Softsol Mail is a free email service provided by Softsol. As of 2012, it had 1.5 billion active users worldwide. A user typically accesses Mail in a web browser or the official mobile app. Softsol also supports the use of email clients via the POP and IMA",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(21,
"Rome",
"C",
"img/Rome1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(22,
"Australia",
"C",
"img/Australia1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(23,
"Maldives",
"C",
"img/Maldives1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(24,
"Los Angeles",
"C",
"img/LosAngeles1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(25,
"New York",
"C",
"img/NewYork1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(26,
"Dubai",
"C",
"img/Dubai1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(27,
"London",
"C",
"img/3_london.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(28,
"New Zealand",
"C",
"img/New_Zealand1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(29,
"West Indies",
"C",
"img/West_Indies1.jpeg",
00.00,
"",
0,
0,
0);
INSERT INTO `SpartanMarketplaceDB`.`Products`
(`productId`,
`productName`,
`productCompany`,
`productImgUrl`,
`productPrice`,
`productShortDesc`,
`productRating`,
`productRatingCount`,
`productAvgRating`)
VALUES
(30,
"Switzerland",
"C",
"img/Switzerland1.jpeg",
00.00,
"",
0,
0,
0);